### ISSUE TITLE
How did I get the Length of the audio track

### ISSUE THREAD

**Issue by stefc** [jimm98y/SharpJaad#3] opened 2023-12-13 08:15 UTC
I want to get the information about the length of the audio track. At the moment I can get the information about SampleRate and SampleSize also the channel count. But for calculation of the track length I need the count of the samples belongs to the track. How I archive this ?

**Comment by jimm98y** [comment] 2023-12-13 15:53
I was not very interested in the MP4 demultiplexer part of the original Java library, that's why I split it from the AAC decoder part. I have only ported the MP4 part with a simple sample app to ensure all is working as it did in Java. For questions related to the usage I'd suggest the original Java repo or StackOverflow. If you find an issue when this C# port is behaving differently from the original Java codebase, please report a new issue with a set of steps to reproduce the problem and I'll look into it.

If you want the simplest way to get the track length, I'd suggest using my other project [SharpMp4Parser](https://github.com/jimm98y/SharpMp4Parser) which can get the track length from the mp4 container. It has a lot more features related to parsing mp4. One way to get the track length would be:
```cs
double lengthInSeconds = (double)
                isoFile.getMovieBox().getMovieHeaderBox().getDuration() /
                isoFile.getMovieBox().getMovieHeaderBox().getTimescale();
```
Because this is not an issue with the library but more a question about the API of the original library, I am closing this.

**Closed by jimm98y** 2023-12-13 15:53 UTC

**Comment by stefc** [comment] 2023-12-13 18:15
I solve it in a similar way using a id3 tag lib for read out the duration of the track

I use your port for decode the frames out of the m4a file and prepare the audio data for ML for detecting jingles in the audio stream, works very good and thxs for your effort on porting the Java code to c#
_

**Comment by stefc** [comment] 2023-12-14 05:18
Thx to your above hint I can solve it directly with SharpJaad. I found the same functionality in the Movie class within the GetDuration method ;) Now I can avoid the usage of TagLib 

<img width="1830" alt="image" src="https://github.com/jimm98y/SharpJaad/assets/464696/271b62e0-1d18-46f3-a281-70f9449dbf2a">
